<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Cards/Commands/" />
    <Folder Include="Cards/Commands/CreateCard/" />
    <Folder Include="Decks/Queries/" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
